# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 20:50


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interlink', '0002_auto_20150421_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='unsubscribed',
            field=models.ManyToManyField(blank=True, related_name='_mailinglist_unsubscribed_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
