# Generated by Django 2.0.2 on 2018-02-12 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlink', '0003_mailinglist_unsubscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='moderators',
            field=models.ManyToManyField(blank=True, help_text='Users who will be sent moderation emails', limit_choices_to={'is_staff': True}, related_name='moderated_mailing_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
