# Generated by Django 2.1.4 on 2019-01-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlink', '0004_auto_20180212_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Set to False to disable this list.'),
        ),
    ]
