# Generated by Django 2.2.9 on 2019-12-30 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interlink', '0005_mailinglist_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='moderators',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='interlink_moderated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='interlink_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='unsubscribed',
            field=models.ManyToManyField(blank=True, related_name='interlink_unsubscribed', to=settings.AUTH_USER_MODEL),
        ),
    ]
