# Generated by Django 3.0.3 on 2020-07-13 14:19

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elocky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elockycred',
            name='code_access',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=128)),
        ),
        migrations.AlterField(
            model_name='elockycred',
            name='num_access',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=128)),
        ),
    ]
