# Generated by Django 2.2.1 on 2019-07-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keymaster', '0005_keymaster_is_syncing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorcode',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
