# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPAccountStatus',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, serialize=False, to=settings.AUTH_USER_MODEL, null=True)),
                ('synchronized', models.BooleanField(default=False)),
                ('ldap_error_message', models.CharField(blank=True, max_length=255)),
                ('ldap_uid', models.CharField(max_length=255, unique=True)),
                ('ldap_dn', models.CharField(blank=True, null=True, max_length=255, unique=True)),
            ],
        ),
    ]
