# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:49


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_motd'),
    ]

    forwardSQL = " \
        DROP TABLE member_motd; \
        ALTER TABLE members_motd RENAME TO member_motd; \
        DROP TABLE member_helptext; \
        ALTER TABLE members_helptext RENAME TO member_helptext; \
        DROP TABLE member_usernotification; \
        ALTER TABLE members_usernotification RENAME TO member_usernotification; \
    "

    reverseSQL = migrations.RunSQL.noop

    operations = [
        # Only needed if you are migrating from an earlier version of Nadine
        # TODO - remove soon
        # migrations.RunSQL(sql=forwardSQL, reverse_sql=reverseSQL)
    ]
