from django.conf.urls import url

from staff import views

urlpatterns = [
    url(r'^$', views.todo),
    url(r'^todo/(?P<key>[^/]+)/$', views.todo_detail),
    url(r'^members/$', views.members),
    url(r'^members/(?P<group>[^/]+)/$', views.members),
    url(r'^export/$', views.export_members),
    url(r'^bcc/$', views.member_bcc),
    url(r'^bcc/(?P<group>[^/]+)/$', views.member_bcc),
    url(r'^search/$', views.member_search),
    url(r'^activity/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$', views.activity_date),
    url(r'^activity/today/$', views.activity_today),
    url(r'^activity/$', views.activity),
    url(r'^activity/list/$', views.activity_list),
    url(r'^pay_all/(?P<username>[^/]+)/$', views.bills_pay_all),
    url(r'^bill/$', views.bills),
    url(r'^bill/list/$', views.bill_list),
    url(r'^bill/run/$', views.run_billing),
    url(r'^bill/(?P<id>\d+)/$', views.bill),
    url(r'^transaction/$', views.transactions),
    url(r'^transaction/(?P<id>\d+)/$', views.transaction),
    url(r'^stats/$', views.stats),
    url(r'^stats/history/$', views.stats_history),
    url(r'^stats/monthly/$', views.stats_monthly),
    url(r'^stats/gender/$', views.stats_gender),
    url(r'^stats/neighborhood/$', views.stats_neighborhood),
    url(r'^stats/membership-history/$', views.stats_membership_history),
    url(r'^stats/membership-days/$', views.stats_membership_days),
    url(r'^stats/graph/$', views.stats_graph),
    url(r'^deposits/$', views.security_deposits),
    url(r'^u/(?P<username>[^/]+)/$', views.member_detail_user),
    url(r'^(?P<member_id>\d+)/$', views.member_detail),
    url(r'^(?P<member_id>\d+)/activity/$', views.member_activity),
    url(r'^(?P<member_id>\d+)/activity/json/$', views.member_activity_json),
    url(r'^(?P<member_id>\d+)/transaction/$', views.member_transactions),
    url(r'^(?P<member_id>\d+)/bill/$', views.member_bills),
    url(r'^(?P<member_id>\d+)/toggle_billing_flag/$', views.toggle_billing_flag),
    url(r'^(?P<member_id>\d+)/membership/$', views.member_membership),
    url(r'^(?P<member_id>\d+)/files/$', views.member_files),
    url(r'^(?P<username>[^/]+)/edit/$', views.member_edit),
    url(r'^membership/(?P<membership_id>\d+)/$', views.membership),
    url(r'^user_reports/$', views.view_user_reports),
    url(r'^usaepay/m/$', views.usaepay_members),
    url(r'^usaepay/void/$', views.usaepay_void),
    url(r'^usaepay/(?P<username>[^/]+)/$', views.usaepay_user),
    url(r'^charges/t/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$', views.usaepay_transactions),
    url(r'^charges/t/today/$', views.usaepay_transactions_today),
    url(r'^xero/(?P<username>[^/]+)/$', views.xero_user),
    url(r'^slack_users/$', views.slack_users),
    url(r'^ip/$', views.view_ip),
]

# Copyright 2009 Office Nomads LLC (http://www.officenomads.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
