# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 18:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadine', '0007_add_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='public_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='zipcode',
            field=models.CharField(blank=True, max_length=16),
        ),

    ]
