# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-15 21:55


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    Membership = apps.get_model("nadine", "Membership")
    for m in Membership.objects.all():
        if m.guest_of:
            m.paid_by = m.guest_of.user
            m.save()

    CoworkingDay = apps.get_model("nadine", "CoworkingDay")
    for d in CoworkingDay.objects.all():
        if d.guest_of:
            d.paid_by = d.guest_of.user
            d.save()

    Bill = apps.get_model("nadine", "Bill")
    for b in Bill.objects.all():
        if b.paid_by:
            b.paid_by_user = b.paid_by.user

def reverse_func(apps, schema_editor):
    Member = apps.get_model("nadine", "Member")
    Membership = apps.get_model("nadine", "Membership")
    for m in Membership.objects.all():
        if m.paid_by:
            m.guest_of = Member.objects.get(user=m.paid_by)
            m.save()

    CoworkingDay = apps.get_model("nadine", "CoworkingDay")
    for d in CoworkingDay.objects.all():
        if d.paid_by:
            d.guest_of = Member.objects.get(user=d.paid_by)
            d.save()

    # Bill = apps.get_model("nadine", "Bill")
    # for b in Bill.objects.all():
    #     #b.member = Member.objects.get(user=b.user)
    #     if b.paid_by_user:
    #         b.paid_by = Member.objects.get(user=b.paid_by_user)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nadine', '0012_auto_20160914_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworkingday',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_day', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_bills_old', to='nadine.Member'),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='coworkingday',
            name='guest_of',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='guest_of',
        ),
        # migrations.RemoveField(
        #     model_name='bill',
        #     name='member',
        # ),
        # migrations.RemoveField(
        #     model_name='bill',
        #     name='paid_by',
        # ),
        # migrations.RenameField(
        #     model_name='bill',
        #     old_name='paid_by_user',
        #     new_name='paid_by',
        # ),
    ]
