# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-15 23:27


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadine', '0013_refactor_guest_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='paid_by',
            new_name='paid_by_old',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='paid_by_user',
            new_name='paid_by',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='paid_by_old',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='member',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='member',
        ),
    ]
