# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-27 20:34


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    EmailAddress = apps.get_model("nadine", "EmailAddress")
    for u in User.objects.exclude(email=''):
        other_users = EmailAddress.objects.filter(email=u.email)
        if other_users:
            for o in other_users:
                print(("Email address '%s' used by both '%s' and '%s'!" % (u.email, u.username, o.user.username)))
        else:
            EmailAddress.objects.create(user=u, email=u.email, is_primary=True)
            if u.profile and u.profile.email2:
                if u.email != u.profile.email2:
                    EmailAddress.objects.create(user=u, email=u.profile.email2, is_primary=False)

def reverse(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    EmailAddress = apps.get_model("nadine", "EmailAddress")
    for u in User.objects.all():
        if u.emailaddress_set.count() > 1:
            all_emails = u.emailaddress_set.all()
            u.profile.email2 = all_emails[1].email
            u.profile.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nadine', '0016_auto_20160918_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('verif_key', models.CharField(max_length=40)),
                ('verified_ts', models.DateTimeField(blank=True, default=None, null=True)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('remote_host', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(forward, reverse),
        migrations.RemoveField(
            model_name='userprofile',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='promised_followup',
        ),
    ]
