# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 21:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadine', '0018_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='url_aboutme',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='url_github',
        ),
    ]
