# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 00:35


from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('nadine', '0021_auto_20161114_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
