# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    pass

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('nadine', '0023_auto_20161122_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('url_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadine.URLType')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='websites',
            field=models.ManyToManyField(blank=True, to='nadine.Website'),
        ),
        migrations.RunPython(forward, reverse),
    ]
