# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 18:34


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nadine', '0024_websites'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberalert',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memberalert',
            name='muted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muted_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memberalert',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
