# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nadine', '0028_new_membership'),
    ]

    operations = [
        # Rename old Bill model
        migrations.RenameModel(
            old_name='Bill',
            new_name='OldBill',
        ),
        migrations.AlterField(
            model_name='oldbill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_bill', to=settings.AUTH_USER_MODEL),
        ),
    ]
