# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 16:47


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nadine', '0030_coworking_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('U', 'Not recorded'), ('M', 'Man'), ('F', 'Woman'), ('O', 'Something else')], default='U', max_length=1),
        ),
    ]
