# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import nadine.models.core


class Migration(migrations.Migration):

    dependencies = [
        ('nadine', '0030_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='default_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(upload_to=nadine.models.core.doc_upload_path),
        ),
    ]
