# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:09
from __future__ import unicode_literals

from django.db import migrations, models


def forward(apps, schema_editor):
    MembershipPlan = apps.get_model("nadine", "MembershipPlan")
    MembershipPackage = apps.get_model("nadine", "MembershipPackage")
    for package in MembershipPackage.objects.all():
        plan = MembershipPlan.objects.filter(name=package.name).first()
        if plan:
            package.enabled = plan.enabled
            package.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('nadine', '0030_new_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippackage',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    migrations.RunPython(forward, reverse),
    ]
