# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 21:22


from django.db import migrations, models
import django.db.models.deletion


def rename_resource(apps, old_key, new_key, new_name):
    Resource = apps.get_model("nadine", "Resource")
    resource = Resource.objects.filter(key=old_key).first()
    if not resource:
        print(("Could not find resouce for key '%s' " % old_key))
        return False
    resource.key = new_key
    resource.name = new_name
    resource.save()
    return True


def forward(apps, schema_editor):
    rename_resource(apps, "room", "event", "Event Hours")


def reverse(apps, schema_editor):
    rename_resource(apps, "event", "room", "Room Booking")


class Migration(migrations.Migration):

    dependencies = [
        ('nadine', '0031_gender'),
    ]

    operations = [
        # New EventLineItem model
        migrations.CreateModel(
            name='EventLineItem',
            fields=[
                ('billlineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nadine.BillLineItem')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line_item', to='nadine.Event')),
            ],
            bases=('nadine.billlineitem',),
        ),

        # Changes to Room model
        migrations.AddField(
            model_name='room',
            name='members_only',
            field=models.BooleanField(default=False),
        ),

        # Changes to the CoworkingDay and CoworkingLineItem models
        migrations.AlterField(
            model_name='coworkingdaylineitem',
            name='day',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line_item', to='nadine.CoworkingDay'),
        ),
        migrations.RemoveField(
            model_name='coworkingday',
            name='bill',
        ),

        # Changes to the Event model
        migrations.AddField(
            model_name='event',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='event',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nadine.Room'),
        ),

        migrations.RunPython(forward, reverse),
    ]
