# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nadine', '0031_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLineItem',
            fields=[
                ('billlineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nadine.BillLineItem')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='nadine.Event')),
            ],
            bases=('nadine.billlineitem',),
        ),
        migrations.AddField(
            model_name='event',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
    ]
