# Generated by Django 2.0.3 on 2018-04-06 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nadine', '0033_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeBillingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(help_text='Customer email address used with Stripe customer record', max_length=254)),
                ('customer_id', models.CharField(help_text='Stripe customer ID used for billing via Stripe', max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
