# Generated by Django 2.0.3 on 2018-04-13 23:26

from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    # We can't do this in migration space
    # UserBill = apps.get_model("nadine", "UserBill")
    # for bill in UserBill.objects.all():
    #     bill.update_cached_totals()
    # print()
    # print("    NOTE: After the migration run './manage.py migrate_21'")
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('nadine', '0034_stripebillingprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItemTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadine.BillLineItem')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the tax', max_length=256)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Tax percentage', max_digits=3)),
                ('resources', models.ManyToManyField(to='nadine.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='lineitemtax',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadine.TaxRate'),
        ),
        migrations.AddField(
            model_name='userbill',
            name='cached_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='userbill',
            name='cached_total_owed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='userbill',
            name='cached_total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='userbill',
            name='cached_total_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),

        migrations.RunPython(forward, migrations.RunPython.noop),

    ]
