# Generated by Django 2.1.4 on 2019-01-03 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadine', '0035_taxes_cached_totals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingLog',
        ),
        migrations.RemoveField(
            model_name='oldbill',
            name='dropins',
        ),
        migrations.RemoveField(
            model_name='oldbill',
            name='guest_dropins',
        ),
        migrations.RemoveField(
            model_name='oldbill',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='oldbill',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='oldbill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='oldmembership',
            name='membership_plan',
        ),
        migrations.RemoveField(
            model_name='oldmembership',
            name='new_membership',
        ),
        migrations.RemoveField(
            model_name='oldmembership',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='oldmembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bills',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='new_payment',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
        migrations.DeleteModel(
            name='OldBill',
        ),
        migrations.DeleteModel(
            name='OldMembership',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
