# Generated by Django 3.1 on 2020-08-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadine', '0038_userprofile_usercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemaillog',
            name='success',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_kids',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='self_employed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='valid_billing',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
