# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 19:34


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comlink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleMailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.EmailField(max_length=254, unique=True)),
                ('access_ts', models.DateTimeField(auto_now=True)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='simple_mailing_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
