# Generated by Django 2.2.9 on 2019-12-30 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comlink', '0002_simplemailinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('subject_prefix', models.CharField(blank=True, max_length=64)),
                ('address', models.EmailField(max_length=254, unique=True)),
                ('access_ts', models.DateTimeField(auto_now=True)),
                ('is_members_only', models.BooleanField(default=True)),
                ('is_opt_out', models.BooleanField(default=False)),
                ('moderators', models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='_mailinglist_moderators_+', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='_mailinglist_subscribers_+', to=settings.AUTH_USER_MODEL)),
                ('unsubscribed', models.ManyToManyField(blank=True, related_name='_mailinglist_unsubscribed_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SimpleMailingList',
        ),
    ]
