# Generated by Django 2.2.9 on 2019-12-31 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comlink', '0004_EmailMessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='mailing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comlink.MailingList'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Set to False to disable this list.'),
        ),
    ]
