import os
import string
import random

from django.contrib.auth.models import User
from django.core.management.base import BaseCommand, CommandError

EXAMPLE_FILE = "nadine/local_settings.example"
SETTINGS_FILE = "nadine/local_settings.py"
PROMPT = '> '

class LocalSettings():

    def __init__(self):
        print("Loading example settings file...")
        with open(EXAMPLE_FILE) as f:
            self.settings = f.readlines()

        self.settings.append("\n# Settings Generated by ./manage.py setup\n")

        print("Generating random SECRET_KEY")
        secret_key = ''.join([random.SystemRandom().choice("{}{}".format(string.ascii_letters, string.digits)) for i in range(63)])
        self.set('SECRET_KEY', secret_key)

    def get_line_number(self, key):
        for i, line in enumerate(self.settings):
            if line.startswith(key):
                return i
        return -1

    def set(self, key, value):
        new_line = '%s = "%s"\n' % (key, value)
        line_number = self.get_line_number(key)
        if line_number >= 0:
            self.settings[line_number] = new_line
        else:
            self.settings.append(new_line)

    def set_database(self, db_name=None, db_user=None, db_pass=None):
        self.settings.append("DATABASES = {\n")
        self.settings.append("    'default': {\n")
        self.settings.append("        'ENGINE': 'django.db.backends.postgresql_psycopg2',\n")
        if db_name:
            self.settings.append("         'NAME': '%s',\n" % db_name)
        if db_user:
            self.settings.append("         'USER': '%s',\n" % db_user)
        if db_pass:
            self.settings.append("         'PASSWORD': '%s',\n" % db_pass)
        self.settings.append("    }\n}\n")

    def save(self):
        print("Writing new settings file...")
        with open(SETTINGS_FILE, 'w') as f:
            f.writelines(self.settings)


class Command(BaseCommand):
    help = "System Setup"
    requires_system_checks = False

    def handle(self, **options):
        local_settings = LocalSettings()

        # Database Setup
        print("Database Name? default: nadinedb")
        db_name = raw_input(PROMPT).strip()
        if not db_name:
            db_name = "nadinedb"
        print("Database User? default: postgres")
        db_user = raw_input(PROMPT).strip()
        if not db_user:
            db_user = "postgres"
        print("Database Password?")
        db_pass = raw_input(PROMPT).strip()
        local_settings.set_database(db_name, db_user, db_pass)
        local_settings.save()

        print ("Migrating database")
        from django.conf import settings
        from django.core import management
        management.call_command("migrate")

        #print User.objects.count()
        # print("We need to create an administrator.")
        # print("Admin First Name?")
        # admin_first_name = raw_input(PROMPT).strip().title()
        # print("Admin Last Name?")
        # admin_last_name = raw_input(PROMPT).strip().title()
        # print("Admin Email Address?")
        # admin_email = raw_input(PROMPT).strip().lower()
        # print("Admin Password?")
        # admin_password = raw_input(PROMPT).strip()
        # admin_username = "%s_%s" % (admin_first_name.lower(), admin_last_name.lower())
        #admin_user = User.objects.create_superuser(admin_username, admin_email, admin_password)
        #admin_user.first_name = admin_first_name
        #admin_user.last_name = admin_last_name
        # print admin_username
        #admin_user.save()
        #print User.objects.count()

        # Timezone

        # Mail Server Setup
